services:
  database:
    image: mysql:9.5.0
    container_name: my_sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e_app_dp
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "7070:80"
    depends_on:
      - database

volumes:
  db_data: